=== svenmeier/jorgan/branches/jorgan-4.0/jorgan-gui/src/main/xml/skin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xs3p.xsl"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://jorgan.sourceforge.net/skin"
	xmlns="http://jorgan.sourceforge.net/skin"
	elementFormDefault="qualified"
>
	<xs:element name="skin">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="styles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="style" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="compositeLayer">
											<xs:sequence>
												<xs:element type="xs:string" name="name" />
											</xs:sequence>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="layer">
		<xs:sequence>
			<xs:element name="anchor">
				<xs:annotation>
					<xs:documentation>
						 Where is this layer positioned when it is smaller than the overall size.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CENTER" />
						<xs:enumeration value="TOP" />
						<xs:enumeration value="TOP_RIGHT" />
						<xs:enumeration value="RIGHT" />
						<xs:enumeration value="BOTTOM_RIGHT" />
						<xs:enumeration value="BOTTOM" />
						<xs:enumeration value="BOTTOM_LEFT" />
						<xs:enumeration value="LEFT" />
						<xs:enumeration value="TOP_LEFT" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="fill">
				<xs:annotation>
					<xs:documentation>
						In which direction to fill this layer when it is smaller than the overall size.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NONE" />
						<xs:enumeration value="HORIZONTAL" />
						<xs:enumeration value="VERTICAL" />
						<xs:enumeration value="BOTH" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element type="xs:int" name="width">
				<xs:annotation>
					<xs:documentation>
						Explicit width, if not specified the width will be determined by this layer's content and padding.  
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:int" name="height">
				<xs:annotation>
					<xs:documentation>
						Explicit height, if not specified the height will be determined by this layer's content and padding.  
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="padding">
				<xs:annotation>
					<xs:documentation>
						What padding should be applied to the size of this layer's content.  
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element type="xs:int" name="top" />
						<xs:element type="xs:int" name="left" />
						<xs:element type="xs:int" name="bottom" />
						<xs:element type="xs:int" name="right" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element type="xs:string" name="binding" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="compositeLayer">
		<xs:complexContent>
			<xs:extension base="layer">
				<xs:sequence>
					<xs:element name="layers">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded" minOccurs="0">
								<xs:element name="composite" type="compositeLayer" />
								<xs:element name="image">
									<xs:annotation>
										<xs:documentation>
											A layer with image content.  
										</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="layer">
												<xs:sequence>
													<xs:element type="xs:string" name="file">
														<xs:annotation>
															<xs:documentation>
																File containing the image content.  
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="border">
														<xs:annotation>
															<xs:documentation>
																What border should be honored to the image when stretching.  
															</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:int" name="top" />
																<xs:element type="xs:int" name="left" />
																<xs:element type="xs:int" name="bottom" />
																<xs:element type="xs:int" name="right" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
								
								<xs:element name="text">
									<xs:annotation>
										<xs:documentation>
											A layer with text content.  
										</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="layer">
												<xs:sequence>
													<xs:element name="alignment">
														<xs:annotation>
															<xs:documentation>
																 Where is the text positioned in a layer with a greater size.
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="CENTER" />
																<xs:enumeration value="TOP" />
																<xs:enumeration value="TOP_RIGHT" />
																<xs:enumeration value="RIGHT" />
																<xs:enumeration value="BOTTOM_RIGHT" />
																<xs:enumeration value="BOTTOM" />
																<xs:enumeration value="BOTTOM_LEFT" />
																<xs:enumeration value="LEFT" />
																<xs:enumeration value="TOP_LEFT" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="font" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
																 Name, style and size for the font of the text or a file containing a font.
															</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="name" />
																<xs:element type="xs:int" name="style" />
																<xs:element type="xs:int" name="size" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="color" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
																 Color for the text.
															</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:short" name="red" />
																<xs:element type="xs:short" name="green" />
																<xs:element type="xs:short" name="blue" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element type="xs:boolean" name="antialiased" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
																 Should text be rendered antialiased.
															</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
								
								<xs:element name="button">
									<xs:annotation>
										<xs:documentation>
											 A composite layer rendering the first contained layer in the pressed state and
											 the second contained layer in the released state. 
										</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="compositeLayer">
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
								
								<xs:element name="slider">
									<xs:annotation>
										<xs:documentation>
											 A composite layer rendering one of the contained layers according to the current position. 
										</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="compositeLayer">
												<xs:sequence>
													<xs:element type="xs:int" name="direction">
														<xs:annotation>
															<xs:documentation>
																 The drag direction:
																 1=left-to-right, 2=right-to-left, 3=top-to-bottom, 4=bottom-to-top 
															</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== svenmeier/jorgan/tags/jorgan-3.21/jorgan-skins/theatre/skin.xml
<skin xmlns="http://jorgan.sourceforge.net/skin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jorgan.sourceforge.net/skin ../../jorgan-gui/src/main/xml/skin.xsd">
  <name>theatre</name>
  <styles>
    <style>
      <anchor>CENTER</anchor>
      <fill>NONE</fill>
      <width>0</width>
      <height>0</height>
      <padding>
        <top>0</top>
        <left>0</left>
        <bottom>0</bottom>
        <right>0</right>
      </padding>
      <layers>
        <image>
          <anchor>CENTER</anchor>
          <fill>NONE</fill>
          <width>0</width>
          <height>0</height>
          <padding>
            <top>0</top>
            <left>0</left>
            <bottom>0</bottom>
            <right>0</right>
          </padding>
          <file>console.png</file>
          <border>
            <top>0</top>
            <left>0</left>
            <bottom>0</bottom>
            <right>0</right>
          </border>
        </image>
      </layers>
      <name>console</name>
    </style>
    <style>
      <anchor>CENTER</anchor>
      <fill>NONE</fill>
      <width>0</width>
      <height>0</height>
      <padding>
        <top>0</top>
        <left>0</left>
        <bottom>0</bottom>
        <right>0</right>
      </padding>
      <layers>
        <image>
          <anchor>CENTER</anchor>
          <fill>BOTH</fill>
          <width>0</width>
          <height>0</height>
          <padding>
            <top>0</top>
            <left>0</left>
            <bottom>0</bottom>
            <right>0</right>
          </padding>
          <file>label.png</file>
          <border>
            <top>16</top>
            <left>16</left>
            <bottom>16</bottom>
            <right>16</right>
          </border>
        </image>
        <text>
          <anchor>CENTER</anchor>
          <fill>NONE</fill>
          <width>0</width>
          <height>0</height>
          <padding>
            <top>4</top>
            <left>8</left>
            <bottom>4</bottom>
            <right>8</right>
          </padding>
          <binding>name</binding>
          <alignment>CENTER</alignment>
          <font>
            <name>Arial</name>
            <style>0</style>
            <size>14</size>
          </font>
          <color>
            <red>0</red>
            <green>0</green>
            <blue>0</blue>
          </color>
          <antialiased>true</antialiased>
        </text>
      </layers>
      <name>label</name>
    </style>
    <style>
      <anchor>CENTER</anchor>
      <fill>NONE</fill>
      <width>0</width>
      <height>0</height>
      <padding>
        <top>0</top>
        <left>0</left>
        <bottom>0</bottom>
        <right>0</right>
      </padding>
      <layers>
        <button>
          <anchor>CENTER</anchor>
          <fill>BOTH</fill>
          <width>0</width>
          <height>0</height>
          <padding>
            <top>8</top>
            <left>8</left>
            <bottom>8</bottom>
            <right>8</right>
          </padding>
          <binding>active</binding>
          <layers>
            <composite>
              <anchor>CENTER</anchor>
              <fill>NONE</fill>
              <width>0</width>
              <height>0</height>
              <padding>
                <top>0</top>
                <left>0</left>
                <bottom>0</bottom>
                <right>0</right>
              </padding>
              <layers>
                <image>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>0</width>
                  <height>0</height>
                  <padding>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <file>white0.png</file>
                  <border>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </border>
                </image>
                <text>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>66</width>
                  <height>48</height>
                  <padding>
                    <top>8</top>
                    <left>4</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <binding>name</binding>
                  <alignment>CENTER</alignment>
                  <font>
                    <name>Arial</name>
                    <style>1</style>
                    <size>12</size>
                  </font>
                  <color>
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                  </color>
                  <antialiased>true</antialiased>
                </text>
              </layers>
            </composite>
            <composite>
              <anchor>CENTER</anchor>
              <fill>NONE</fill>
              <width>0</width>
              <height>0</height>
              <padding>
                <top>0</top>
                <left>0</left>
                <bottom>0</bottom>
                <right>0</right>
              </padding>
              <layers>
                <image>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>0</width>
                  <height>0</height>
                  <padding>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <file>white1.png</file>
                  <border>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </border>
                </image>
                <text>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>66</width>
                  <height>48</height>
                  <padding>
                    <top>25</top>
                    <left>4</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <binding>name</binding>
                  <alignment>CENTER</alignment>
                  <font>
                    <name>Arial</name>
                    <style>1</style>
                    <size>12</size>
                  </font>
                  <color>
                    <red>50</red>
                    <green>50</green>
                    <blue>50</blue>
                  </color>
                  <antialiased>true</antialiased>
                </text>
              </layers>
            </composite>
          </layers>
        </button>
      </layers>
      <name>white</name>
    </style>
    <style>
      <anchor>CENTER</anchor>
      <fill>NONE</fill>
      <width>0</width>
      <height>0</height>
      <padding>
        <top>0</top>
        <left>0</left>
        <bottom>0</bottom>
        <right>0</right>
      </padding>
      <layers>
        <button>
          <anchor>CENTER</anchor>
          <fill>BOTH</fill>
          <width>0</width>
          <height>0</height>
          <padding>
            <top>8</top>
            <left>8</left>
            <bottom>8</bottom>
            <right>8</right>
          </padding>
          <binding>active</binding>
          <layers>
            <composite>
              <anchor>CENTER</anchor>
              <fill>NONE</fill>
              <width>0</width>
              <height>0</height>
              <padding>
                <top>0</top>
                <left>0</left>
                <bottom>0</bottom>
                <right>0</right>
              </padding>
              <layers>
                <image>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>0</width>
                  <height>0</height>
                  <padding>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <file>red0.png</file>
                  <border>
                    <top>0</top>
                    <left>0</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </border>
                </image>
                <text>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>66</width>
                  <height>48</height>
                  <padding>
                    <top>8</top>
                    <left>4</left>
                    <bottom>0</bottom>
                    <right>0</right>
                  </padding>
                  <binding>name</binding>
                  <alignment>CENTER</alignment>
                  <font>
                    <name>Arial</name>
                    <style>1</style>
                    <size>12</size>
                  </font>
                  <color>
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                  </color>
                  <antialiased>true</antialiased>
                </text>
              </layers>
            </composite>
            <composite>
              <anchor>CENTER</anchor>
              <fill>NONE</fill>
              <width>0</width>
              <height>0</height>
              <padding>
                <top>0</top>
                <left>0</left>
                <bottom>0</bottom>
                <right>0</right>
              </padding>
              <layers>
                <image>
                  <anchor>TOP</anchor>
                  <fill>NONE</fill>
                  <width>0</width>
